### ISSUE TITLE
Remove CQRS Pattern

### ISSUE THREAD

**Issue by Mentioum** [diegostamigni/cc-catalog#1]
Please remove the CQRS pattern from the project and replace it with front to back monolith structure please.

(Basically simplify it)

REST <-> Handler <-> Storage

**Comment by diegostamigni** [comment]
Fixed in 335eed98adf74ea967abd94bc539baf59f292f2d

Also, I added some unit tests within the `rest` package as complement (with queries/mutation mocked).
