### ISSUE TITLE
Fix Improper Error Handling

### ISSUE THREAD

**Issue by Mentioum** [diegostamigni/cc-catalog#3]
- not returning error from function.
- committing and mutating on the already discarded transaction, will cause an error

https://github.com/diegostamigni/cc-catalog/blob/be09eeb298aceec2b0fce5da18d685e26ca5e7e3/database/dgraph/command/command.go#L16

**Comment by diegostamigni** [comment]
was fixed already in newer commit 70a9fea0de197247d50db87c4c127cf446b5d268
